run:
  timeout: 5m

linters:
  enable-all: false
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused

linters-settings:
  govet:
    enable-all: false

issues:
  exclude-rules:
    # Ignore errors from exec.Command().Run() used in fire-and-forget system calls
    - path: internal/system/rules.go
      linters: [errcheck]
